name: GH-Pages

on:
  push:
    branches: [hugo-migration]

  pull_request:
    branches: [hugo-migration]

  workflow_dispatch:


jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.164.0'
          extended: true

      - name: Build website
        run: hugo --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: public
          clean: true
